/* -*- mode: c++; indent-tabs-mode: nil -*- */
/** @file amqp-module.h amqp module header file */
/*
    Qore amqp module

    Copyright (C) 2026 Qore Technologies, s.r.o.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef _QORE_AMQP_MODULE_H
#define _QORE_AMQP_MODULE_H

#include <qore/Qore.h>
#include <qore/QoreSandboxManager.h>
#include <qore/qore_thread.h>

// Forward declarations
class QoreAmqpConnection;
class QoreAmqpMessage;

// Hashdecl init functions (generated by QPP from QC_AmqpConnection.qpp)
DLLLOCAL TypedHashDecl* init_hashdecl_AmqpConnectionOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_AmqpSslOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_AmqpSaslOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_AmqpDeliveryInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_AmqpSendOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_AmqpReceiveOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_AmqpFilterOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_AmqpAddressInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_AmqpQueueInfo(QoreNamespace& ns);

// Hashdecl init functions (generated by QPP from QC_AmqpMessage.qpp)
DLLLOCAL TypedHashDecl* init_hashdecl_AmqpMessageProperties(QoreNamespace& ns);

// Global hashdecl pointers (initialized in amqp-module.cpp)
extern const TypedHashDecl* hashdeclAmqpConnectionOptions;
extern const TypedHashDecl* hashdeclAmqpSslOptions;
extern const TypedHashDecl* hashdeclAmqpSaslOptions;
extern const TypedHashDecl* hashdeclAmqpDeliveryInfo;
extern const TypedHashDecl* hashdeclAmqpSendOptions;
extern const TypedHashDecl* hashdeclAmqpReceiveOptions;
extern const TypedHashDecl* hashdeclAmqpFilterOptions;
extern const TypedHashDecl* hashdeclAmqpMessageProperties;
extern const TypedHashDecl* hashdeclAmqpAddressInfo;
extern const TypedHashDecl* hashdeclAmqpQueueInfo;

// Class init functions (generated by QPP)
DLLLOCAL QoreClass* initAmqpConnectionClass(QoreNamespace& ns);
DLLLOCAL QoreClass* initAmqpMessageClass(QoreNamespace& ns);

// Class and class ID pointers (defined by QPP-generated code)
extern QoreClass* QC_AMQPCONNECTION;
extern qore_classid_t CID_AMQPCONNECTION;
extern QoreClass* QC_AMQPMESSAGE;
extern qore_classid_t CID_AMQPMESSAGE;

// Namespace
extern QoreNamespace AmqpNs;

#endif // _QORE_AMQP_MODULE_H
